### PR TITLE
Fix/edit some python-y things, add write out to file feature

### PR DESCRIPTION
**Pull request by xzinkus**
Feel free to reject this pull with answers to the `TODO` questions I added in the code comments regarding lists of dictionaries. I can refactor those and make another pull request if you decide they're unnecessary.

### CODE REVIEW

**Comment by DeltaHeavy** [comment]
`ping mandatory.io`

**Comment by mandatoryprogrammer** [comment]
Hey @DeltaHeavy I'm getting the following when I run this:
```python
Traceback (most recent call last):
  File "./xssless.py", line 505, in <module>
    main()
  File "./xssless.py", line 489, in main
    requestList = get_burp_list(inputfile)
  File "./xssless.py", line 28, in get_burp_list
    tmpDict[item.tag] = b64decode(item.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```

Do you experience this as well? Super sorry about getting to this late - Github didn't notify me.

**Comment by DeltaHeavy** [comment]
Ah yes, that's because if statements are a complicated, advanced control
flow mechanism. I'll drop in the edit today haha.

On Fri, May 27, 2016, 11:51 PM Matthew Bryant <notifications@github.com>
wrote:

> Hey @DeltaHeavy <https://github.com/DeltaHeavy> I'm getting the following
> when I run this:
>
> Traceback (most recent call last):
>   File "./xssless.py", line 505, in <module>
>     main()
>   File "./xssless.py", line 489, in main
>     requestList = get_burp_list(inputfile)
>   File "./xssless.py", line 28, in get_burp_list
>     tmpDict[item.tag] = b64decode(item.text)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 76, in b64decode
>     raise TypeError(msg)TypeError: Incorrect padding
>
> Do you experience this as well? Super sorry about getting to this late -
> Github didn't notify me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mandatoryprogrammer/xssless/pull/5#issuecomment-222293769>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFOJX9UxhPYwFELYcMzFGqCyXtxkqS_sks5qF-XUgaJpZM4IJTPP>
> .
>
-- 
Max Zinkus

**Comment by DeltaHeavy** [comment]
That should do it

**Comment by mandatoryprogrammer** [comment]
Thanks for the pull request! Also, why did you make me look at this terrible code I wrote again? I have variable names literally called `hue` in here. Dear god.

**Pull request merged**
